services:
  - type: web
    name: Poly-Chatbot
    runtime: python
    region: singapore
    plan: free 
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
